name: 'Build, Test, and Publish Client Library'
description: 'Builds the project'
inputs:
  client-library-name:
    description: 'The client library name'
    required: false
  deploy-token:
    description: 'The deploy token'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        cd src
        dotnet restore 
        dotnet build --configuration Release --no-restore
        dotnet test UnitTests/UnitTests.csproj
      shell: bash
    - name: Deploy to Development?
      if: |
         github.ref == 'refs/heads/dev' ||
         contains(github.ref, 'refs/heads/feature')
      run: |
        echo "Environment=Development" >> $GITHUB_ENV
      shell: bash
    - name: Deploy to Staging?
      if: |
         contains(github.ref, 'refs/heads/release')     
      run: |
         echo "Environment=Staging" >> $GITHUB_ENV            
      shell: bash
    - name: Deploy to Production?
      if: |
         contains(github.ref, 'refs/heads/release')     
      run: |
         echo "Environment=Staging" >> $GITHUB_ENV            
      shell: bash
    - name: Deploy to Production?
      if: |
         github.event.release.prerelease == false &&
         github.event_name == 'release'
      run: |
        echo "Environment=Production" >> $GITHUB_ENV
      shell: bash
    - uses: chrnorm/deployment-action@releases/v1
      name: Deploy
      if: |
         env.Environment != 'null'
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Nuget Pack
      if: |
          ${{ inputs.client-library-name }} != null &&
          ${{ inputs.client-library-name }} != ''
      run: |  
        cd src        
        dotnet pack Client/Client.csproj  -c Release -o ../nuget/ /p:IncludeSymbols=false -p:PackageVersion=${{ steps.gitversion.outputs.majorMinorPatch }}+${{ steps.gitversion.outputs.shortSha }}
      shell: bash
    - name: Nuget Push
      if: |
          ${{ inputs.client-library-name }} != null &&
          ${{ inputs.client-library-name }} != ''
      run: |  
        cd src
        cd ../nuget/
        dotnet nuget push ${{inputs.client-library-name}}.${{ steps.gitversion.outputs.majorMinorPatch }}.nupkg --source github --api-key $${{ inputs.deploy-token }} --skip-duplicate
      shell: bash
      id: deployment
      with:
        token: ${{ inputs.deploy-token }}
        environment: ${{env.Environment}}
        ref: ${{ github.ref }}