name: 'Build, Test, and Publish Client Library'
description: 'Builds the project'
inputs:
  deploy-token:
    description: "The deploy token"
    required: true
  deploy-to-environment:
    description: "The environment to deploy to"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - uses: actions/checkout@v2
    - name: Merge and then build and test
      if: |
         contains(github.ref, 'refs/heads/feature')
      run: |
        git checkout dev
        git pull
        git checkout ${{ github.ref_name }}
        git merge dev
        cd src
        dotnet restore 
        dotnet build --configuration Release --no-restore
        dotnet test UnitTests/UnitTests.csproj
      shell: bash
    - uses: actions/checkout@v2
    - name: Build and Test
      if: |
         !contains(github.ref, 'refs/heads/feature')
      run: |
        cd src
        dotnet restore 
        dotnet build --configuration Release --no-restore
        dotnet test UnitTests/UnitTests.csproj
      shell: bash
    - name: Deploy to Development?
      if: |
         github.ref == 'refs/heads/dev' ||
         contains(github.ref, 'refs/heads/feature')
      run: |
        echo "Environment=dev" >> $GITHUB_ENV
      shell: bash
    - name: Deploy to Staging?
      if: |
         github.ref == 'refs/heads/stage' ||
         contains(github.ref, 'refs/heads/release')     
      run: |
         echo "Environment=stage" >> $GITHUB_ENV            
      shell: bash     
    - name: Manual Deploy?
      if: (inputs.deploy-to-environment == 'dev' || inputs.deploy-to-environment == 'stage' || inputs.deploy-to-environment == 'prod')
      run: |
         echo Environment=${{inputs.deploy-to-environment}} >> $GITHUB_ENV
      shell: bash
    - name: Prod?
      if: (inputs.deploy-to-environment == 'prod' && github.ref != 'refs/heads/master')
      run: |
         echo "Only Master branch can release to production"
         echo Environment=null >> $GITHUB_ENV
      shell: bash
    - uses: chrnorm/deployment-action@releases/v2
      name: Deploy
      if: ${{ (env.Environment == 'dev' || env.Environment == 'stage' || env.Environment == 'prod') }}
      with:
        token: ${{ inputs.deploy-token }}
        environment: ${{ env.Environment }}
        ref: ${{ github.ref }}